# Generated by Django 4.2.7 on 2023-11-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('natural', 'ナチュラル'), ('beautiful', 'きれいめ'), ('casual', 'カジュアル'), ('cute', '可愛い系'), ('cool', 'クール系'), ('mode', 'モード系')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
