# Generated by Django 4.2.7 on 2023-11-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='target',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
